# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'XTToolSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XTToolSwift
  pod 'Alamofire', '5.6.4'
  pod 'CodableWrapper'

  target 'XTToolSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XTToolSwiftUITests' do
    # Pods for testing
  end

end